import { IncomingMessage, Server } from "node:http";
import {WebSocketServer, WebSocket, RawData} from "ws"
import {Duplex} from "node:stream";
import {ConfigService} from "../../services/config/config.service.js";
import {LoggerService} from "../../services/logger/logger.service.js";


export interface RelayWebSocket extends WebSocket {
	// A unique peer identifier generated by the server, used for directing messages.
	pid: string
	// The public key identifier used to connect peers together in the relay.
	publicKey: string
	// Measuring connection activity to close unresponsive sockets
	isAlive: boolean
}

export class RelayServer {
	#wss: WebSocketServer
	#connectionCheck: NodeJS.Timeout

	constructor(
		server: Server,
		private readonly configService: ConfigService,
		private readonly loggerService: LoggerService,
	) {
		this.#wss = new WebSocketServer({ noServer: true });

		server.on("upgrade", this.handleServerUpgrade.bind(this));
		this.#wss.on("connection", this.handleConnection.bind(this));
		this.#wss.on("close", this.handleClose.bind(this));

		this.loggerService.info("server", `started connection checks every ${this.configService.config().relay.connectionCheckInterval}ms`)
		this.#connectionCheck = setInterval(this.runConnectionCheck.bind(this), this.configService.config().relay.connectionCheckInterval);
	}

	async handleServerUpgrade(req: IncomingMessage, socket: Duplex, head: Buffer) {
		if (!this.configService.config().server.allowedOrigins.includes("*")) {
			if (!req.headers.origin || !this.configService.config().server.allowedOrigins.includes(req.headers.origin)) {
				// todo: send error response of some kind?
				this.loggerService.warn("connection", "denied connection due to invalid origin");
				socket.destroy();
				return;
			}
		}

		if (this.configService.config().relay.accessSecret) {
			const adminToken = req.headers["sec-websocket-protocol"];
			if (typeof adminToken !== "string" || adminToken !== this.configService.config().relay.accessSecret) {
				// todo: send error response of some kind?
				this.loggerService.warn("connection", "denied connection due to missing or invalid admin token");
				socket.destroy();
				return;
			}
		}

		const url = new URL(`http://localhost:0${req.url}`);
		if (!(url.pathname === "/v1" || url.pathname === "/v1/")) {
			// todo: send error response of some kind?
			this.loggerService.warn("connection", "denied connection due to invalid path");
			socket.destroy()
			return;
		}

		const relayId = url.searchParams.get("relayId");
		const peerId = url.searchParams.get("peerId");
		if (!relayId || !peerId) {
			// todo: send error response of some kind?
			this.loggerService.warn("connection", "denied connection due to missing relayId/peerId");
			socket.destroy()
			return;
		}

		// @ts-ignore --- Using custom type which expands WebSocket type with metadata
		this.#wss.handleUpgrade(req, socket, head, async (socket: RelayWebSocket) => {
			socket.pid = peerId;
			socket.publicKey = relayId;
			socket.isAlive = true;
			this.#wss.emit("connection", socket, req);
		})
	}

	handleConnection(ws: RelayWebSocket) {
		this.loggerService.info("connection", `peer '${ws.pid}' connected to relay '${ws.publicKey}'`)

		// todo: is this needed?
		ws.on("error", (e) => {
			this.loggerService.error("server", `encountered error with peer '${ws.pid}'`, e)
		});

		ws.on("message", async (data, isBinary) => {
			// todo: validate to a set of expected messages?
			// todo: apply rate limiting/abuse protection for clients?
			this.handleMessage(ws, data, isBinary)
		});

		ws.on("close", async () => {
			this.loggerService.info("connection", `peer '${ws.pid}' disconnecting from relay '${ws.publicKey}'`)
		})
	}

	handleClose() {
		this.loggerService.info("server", "server closing, stopping connection checks")
		clearInterval(this.#connectionCheck)
	}

	handleMessage(sourceSocket: RelayWebSocket, data: RawData, isBinary?: boolean) {
		const message = isBinary ? data : data.toString();

		const relaySocket = (sourceSocket as RelayWebSocket)
		relaySocket.isAlive = true

		if (message === "pong") return
		if (message === "ping") {
			relaySocket.send("pong")
			return;
		}

		let targetPeerId: string | null = null;
		if (typeof message === "string") {
			try {
				const parsed = JSON.parse(message);
				if (parsed.targetPeerId) {
					targetPeerId = parsed.targetPeerId ? parsed.targetPeerId : null;
				}
			}
			catch (error) {
				targetPeerId = null;
			}
		}

		if (targetPeerId) {
			// todo: this forEach might scale badly with lots of connected sockets?
			// If so, sockets could be stored in a {relayId: socket[]} map to avoid looping over all clients.
			this.#wss.clients.forEach((client) => {
				if ((client as RelayWebSocket).pid === targetPeerId) {
					client.send(data, {binary: isBinary})
				}
			})
		}
		else {
			// todo: this forEach might scale badly with lots of connected sockets?
			// If so, sockets could be stored in a {relayId: socket[]} map to avoid looping over all clients.
			this.#wss.clients.forEach((client) => {
				if (client !== relaySocket && (client as RelayWebSocket).publicKey === relaySocket.publicKey && client.readyState === WebSocket.OPEN) {
					client.send(data, {binary: isBinary})
				}
			})
		}
	}

	runConnectionCheck() {
		this.loggerService.debug("server", `running connection health check for ${this.#wss.clients.size} total peers`);

		this.#wss.clients.forEach((ws) => {
			const relaySocket = ws as RelayWebSocket;
			if (!relaySocket.isAlive) {
				this.loggerService.info("connection", `disconnecting peer '${relaySocket.pid}' from relay '${relaySocket.publicKey}' due to failed connection check`)
				return relaySocket.terminate();
			}
			relaySocket.isAlive = false;
			relaySocket.send("ping");
		});
	}
}
